<?php

namespace App\Notifications;

use Illuminate\Bus\Queueable;
use Illuminate\Notifications\Messages\MailMessage;
use Illuminate\Notifications\Notification;

class DevNextResetPassword extends Notification
{
    use Queueable;

    /**
     * The password reset token generated by Fortify.
     */
    public string $token;

    /**
     * The 6-digit verification code.
     */
    public string $code;

    /**
     * Create a new notification instance.
     */
    public function __construct(string $token, string $code)
    {
        $this->token = $token;
        $this->code = $code;
    }

    /**
     * Get the notification's delivery channels.
     *
     * @return array<int, string>
     */
    public function via(object $notifiable): array
    {
        return ['mail'];
    }

    /**
     * Get the mail representation of the notification.
     */
    public function toMail(object $notifiable): MailMessage
    {
        $resetUrl = url('/reset-password/' . $this->token . '?email=' . urlencode($notifiable->getEmailForPasswordReset()));

        return (new MailMessage)
            ->subject('Reset your DevNext password')
            ->view('emails.password-reset', [
                'user' => $notifiable,
                'code' => $this->code,
                'resetUrl' => $resetUrl,
            ]);
    }

    /**
     * Get the array representation of the notification.
     *
     * @return array<string, mixed>
     */
    public function toArray(object $notifiable): array
    {
        return [
            //
        ];
    }
}
